# Generated by Django 4.0.10 on 2023-10-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
