# Generated by Django 4.0.10 on 2023-08-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departments',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
