# Generated by Django 4.2.4 on 2023-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concession_app", "0002_customuser_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=50, null=True)),
                ("expire_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
