# Generated by Django 4.0.10 on 2023-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession_app', '0003_concessionadmin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionapplication',
            name='state',
            field=models.CharField(default='applied', max_length=25),
        ),
    ]
